spring:
  cloud:
    stream:
      bindings:
        input-channel-1:
          destination: foobar
      kafka:
        streams:
          binder:
            application-id: springBootStream
            brokers: 'localhost:9092'
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde